# Generated by Django 4.2.1 on 2023-11-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_food_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "approved"),
                    ("pending", "pending"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
