# Generated by Django 4.2.1 on 2023-11-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_food_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
    ]
